# yaml-language-server: $schema=https://raw.githubusercontent.com/slackapi/manifest-schema/main/manifest.schema.json
# Slack app manifest for https://app.slack.com/app-settings/T0266FRGM/A07QFDAV272 in production
# mode. Edit Request URL at your own risk.
display_information:
  name: Hack Club Leeks
  description: "Found a leek? React with :leeks: or use the Flag as leek shortcut."
  background_color: "#15a372"
  long_description: 'I am a bot developed by @ajhalili2006 for the #hackclub-leeks channel, usually trigger through the :leeks: reaction or "Flag as leek" shortcut. Please do not use this to leak PII or confidential HQ stuff.'
features:
  bot_user:
    display_name: Hack Club Leeks
    always_online: false
  shortcuts:
    - name: Flag as leek
      type: message
      callback_id: leeks_flagops
      description: "Discreetly forward this message to #hackclub-leeks without the :leeks: reaction"
  slash_commands:
    - command: /leeks
      description: Access the Leeks bot command
      usage_hint: "[help|...]"
      should_escape: true
      url: https://leeksbot.api.recaptime.dev/slack/events
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:history
      - channels:join
      - channels:read
      - chat:write
      - commands
      - emoji:read
      - groups:history
      - groups:read
      - im:read
      - im:write
      - mpim:read
      - reactions:read
      - usergroups:read
      - usergroups:write
      - users:read
settings:
  event_subscriptions:
    request_url: https://leeksbot.api.recaptime.dev/slack/events
    bot_events:
      - reaction_added
      - reaction_removed
      - channel_created
      - channel_unarchive
  interactivity:
    is_enabled: true
    request_url: https://leeksbot.api.recaptime.dev/slack/events
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
