name: Deployments

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nest:
    name: Hack Club Nest
    runs-on: ubuntu-24.04
    environment: 
      name: nest/production
      url: https://leeksbot.ajhalili2006.hackclub.app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git pull stuff
        run: echo todo
  docs-site:
    name: Documentation Site
    runs-on: ubuntu-24.04
    environment: 
      name: docs/production
      url: https://leeksbot.hackclub.lorebooks.wiki
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run docs:build