name: Deployments

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nest:
    name: Hack Club Nest
    runs-on: ubuntu-24.04
    environment: 
      name: nest/production
      url: https://leeksbot.ajhalili2006.hackclub.app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Doppler Secrets
        id: doppler
        uses: DopplerHQ/secrets-fetch-action@v1.3.0
        with:
          doppler-token: ${{secrets.DOPPLER_TOKEN}}       
      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{steps.doppler.outputs.NEST_SSH_PRIVATE_KEY}}
          name: ajhalili2006-passwordless
          config: |
            Host nest
              Hostname hackclub.app
              User ajhalili2006
              IdentityFile ~/.ssh/ajhalili2006-passwordless
      - name: Update code on nest
        run: |
          ssh nest git -C /home/ajhalili2006/git/leeksbot pull
          ssh nest bash -c "cd /home/ajhalili2006/git/leeksbot && npm i && npx prisma generate"
          ssh nest bash -c "cp -v /home/ajhalili2006/git/leeksbot/lib/leeksbot-nest.service /home/ajhalili2006/.config/systemd/user && systemctl --user daemon-reload"
          ssh nest systemctl restart leeksbot-nest